'use client'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { Bell,Home,LocateFixed,Map as MapIcon,Search,TrendingUp,UsersRound,UserRound } from 'lucide-react'
import Composer from '@/components/Composer'
import Feed,{Post} from '@/components/Feed'
import NearbyMap from '@/components/NearbyMap'
import AuthPanel from '@/components/AuthPanel'
import GroupsPanel from '@/components/GroupsPanel'
import { supabase } from '@/lib/supabase'

type Loc={latitude:number;longitude:number}
type RequestItem={id:string;question:string;location_name?:string|null;latitude?:number|null;longitude?:number|null;display_name?:string|null;created_at:string;expires_at:string;is_resolved:boolean;responses_count:number}
function ago(d:string){const m=Math.max(1,Math.floor((Date.now()-new Date(d).getTime())/60000));return m<60?`לפני ${m} דק׳`:`לפני ${Math.floor(m/60)} שע׳`}
const trendStyle=['trend-blue','trend-coral','trend-green','trend-purple','trend-orange']
const trendEmoji=['🚙','🏖️','🛒','🚦','🎫']

export default function HomePage(){
 const [posts,setPosts]=useState<Post[]>([]);const [requests,setRequests]=useState<RequestItem[]>([]);const [composer,setComposer]=useState<'status'|'request'|null>(null);const [answerId,setAnswerId]=useState<string|null>(null);const [query,setQuery]=useState('');const [toast,setToast]=useState('');const [tab,setTab]=useState<'home'|'requests'|'groups'|'map'|'profile'>('home');const [location,setLocation]=useState<Loc|null>(null)
 const load=useCallback(async()=>{if(!supabase)return;const now=new Date().toISOString();const [p,r]=await Promise.all([supabase.from('posts').select('*').gt('expires_at',now).eq('is_active',true).order('created_at',{ascending:false}).limit(100),supabase.from('status_requests').select('*').gt('expires_at',now).order('created_at',{ascending:false}).limit(100)]);if(p.data)setPosts(p.data as Post[]);if(r.data)setRequests(r.data as RequestItem[])},[])
 useEffect(()=>{load();const db=supabase;if(!db)return;const ch=db.channel('statusnow-live').on('postgres_changes',{event:'*',schema:'public',table:'posts'},load).on('postgres_changes',{event:'*',schema:'public',table:'status_requests'},load).on('postgres_changes',{event:'*',schema:'public',table:'confirmations'},load).subscribe();return()=>{db.removeChannel(ch)}},[load])
 function gps(){navigator.geolocation?.getCurrentPosition(p=>{setLocation({latitude:p.coords.latitude,longitude:p.coords.longitude});setToast('המיקום שלך פעיל');setTimeout(()=>setToast(''),1500)},()=>{setToast('אפשר להמשיך גם בלי מיקום');setTimeout(()=>setToast(''),1800)})}
 const filtered=useMemo(()=>posts.filter(p=>!query.trim()||p.text.toLowerCase().includes(query.toLowerCase())||(p.location_name||'').toLowerCase().includes(query.toLowerCase())),[posts,query])
 const trends=useMemo(()=>{const m=new globalThis.Map<string,number>();[...posts.map(p=>p.text),...requests.map(r=>r.question)].forEach(t=>t.split(/\s+/).filter(w=>w.length>3).forEach(w=>m.set(w,(m.get(w)||0)+1)));const learned=[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([x,count])=>({label:x,count}));const fallback=[{label:'מצב תנועה באיילון',count:120},{label:'גלים בחוף הילטון',count:85},{label:'מלאי בסופר',count:67}];return learned.length>=3?learned:[...learned,...fallback].slice(0,3)},[posts,requests])
 function created(){load();setToast('פורסם בזמן אמת ✓');setTimeout(()=>setToast(''),1800)}
 return <main className="app-shell reference-shell"><div className="reference-page"><header className="reference-header"><div className="reference-logo">Status<span>Now</span></div><div className="reference-tagline">מה קורה עכשיו סביבך?</div></header>
 {tab==='home'&&<><div className="reference-composer" onClick={()=>setComposer('status')}><div className="reference-avatar">👤</div><div className="reference-composer-text">מה קורה כאן עכשיו?! <span>💬</span></div></div><div className="reference-search"><Search size={22}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="חפש לפי מקום או תוכן..."/></div><div className="reference-section-title"><div><TrendingUp size={18}/><strong>פופולרי עכשיו</strong></div></div><div className="reference-trends">{trends.map((t,i)=><button key={`${t.label}-${i}`} className={`reference-trend-card ${trendStyle[i%trendStyle.length]}`} onClick={()=>setQuery(t.label)}><div className="trend-emoji">{trendEmoji[i%trendEmoji.length]}</div><div className="trend-title">{t.label}</div><div className="trend-stats">{Math.max(t.count,12)} בקשות · {Math.max(Math.round(t.count*.38),5)} עדכונים</div></button>)}</div><div className="reference-feed"><Feed posts={filtered} onRefresh={load}/></div></>}
 {tab==='requests'&&<><div className="reference-page-heading"><div><h2>בקשות פתוחות</h2><p>שאל אנשים שנמצאים שם עכשיו וקבל תשובה בזמן אמת</p></div><button onClick={()=>setComposer('request')}>＋ בקשה חדשה</button></div><div className="requests-summary"><div><b>{requests.filter(r=>!r.is_resolved).length}</b><span>ממתינות</span></div><div><b>{requests.filter(r=>r.is_resolved).length}</b><span>נענו</span></div></div><div className="requests-list">{requests.map(r=><article className={`request-card ${r.is_resolved?'resolved':''}`} key={r.id}><div className="request-top"><span>{r.is_resolved?'נענה ✓':'ממתין לעדכון ⏳'}</span><small>{ago(r.created_at)}</small></div><h3>{r.question}</h3>{r.location_name&&<p>📍 {r.location_name}</p>}<div className="request-bottom"><span>{r.responses_count||0} תשובות</span><button onClick={()=>setAnswerId(r.id)}>ענה עכשיו</button></div>{posts.filter(p=>p.request_id===r.id).map(p=><div className="inline-response" key={p.id}><strong>{p.display_name||'אורח'}</strong> · {p.text}</div>)}</article>)}{requests.length===0&&<div className="empty">אין כרגע בקשות פתוחות. אפשר לפרסם את הראשונה.</div>}</div></>}
 {tab==='groups'&&<GroupsPanel/>}
 {tab==='map'&&<><div className="reference-page-heading"><div><h2>מפה חיה</h2><p>עדכונים פעילים סביב המיקום שלך</p></div><button onClick={gps}><LocateFixed size={17}/> {location?'רענן GPS':'הפעל GPS'}</button></div><NearbyMap posts={posts} userLocation={location}/></>}
 {tab==='profile'&&<AuthPanel embedded/>}
 </div>
 <nav className="reference-bottom-nav"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><Home/><span>ראשי</span></button><button className={tab==='requests'?'active':''} onClick={()=>setTab('requests')}><Bell/><span>בקשות</span></button><button className={tab==='groups'?'active':''} onClick={()=>setTab('groups')}><UsersRound/><span>קבוצות</span></button><button className={tab==='map'?'active':''} onClick={()=>{setTab('map');if(!location)gps()}}><MapIcon/><span>מפה</span></button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}><UserRound/><span>הרשם</span></button></nav>
 {composer&&<Composer mode={composer} onClose={()=>setComposer(null)} onCreated={created} userLocation={location}/>} {answerId&&<Composer mode="status" requestId={answerId} onClose={()=>setAnswerId(null)} onCreated={created} userLocation={location}/>} {toast&&<div className="toast">{toast}</div>}</main>
}
