'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { BellRing, Home, LocateFixed, MapPinned, UserRound } from 'lucide-react'
import Composer from '@/components/Composer'
import Feed, { Post } from '@/components/Feed'
import NearbyMap from '@/components/NearbyMap'
import AuthPanel from '@/components/AuthPanel'
import { hasSupabaseEnv, supabase } from '@/lib/supabase'

const demoPosts: Post[] = [
  { id:'demo-1',kind:'status',text:'עומס כבד עכשיו באיילון דרום באזור השלום. נוסעים ממש לאט.',location_name:'איילון דרום, תל אביב',latitude:32.0735,longitude:34.7932,media_url:'https://images.unsplash.com/photo-1494522358652-f30e61a60313?auto=format&fit=crop&w=1200&q=80',media_type:'image',created_at:new Date(Date.now()-8*60000).toISOString(),expires_at:new Date(Date.now()+3*3600000).toISOString(),likes_count:14,comments_count:5 },
  { id:'demo-2',kind:'request',text:'מישהו נמצא עכשיו במשרד הרישוי חולון? כמה זמן התור בערך?',location_name:'משרד הרישוי חולון',latitude:32.0158,longitude:34.7735,created_at:new Date(Date.now()-18*60000).toISOString(),expires_at:new Date(Date.now()+5*3600000).toISOString(),likes_count:3,comments_count:2 },
  { id:'demo-3',kind:'status',text:'ים מעולה הבוקר, גלים חזקים יחסית והרבה גולשים במים.',location_name:'חוף הילטון, תל אביב',latitude:32.0896,longitude:34.7691,media_url:'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=80',media_type:'image',created_at:new Date(Date.now()-26*60000).toISOString(),expires_at:new Date(Date.now()+2*3600000).toISOString(),likes_count:21,comments_count:4 }
]

type Loc = { latitude:number; longitude:number }
function distanceKm(a:Loc,b:Loc){ const R=6371,dLat=(b.latitude-a.latitude)*Math.PI/180,dLon=(b.longitude-a.longitude)*Math.PI/180; const x=Math.sin(dLat/2)**2+Math.cos(a.latitude*Math.PI/180)*Math.cos(b.latitude*Math.PI/180)*Math.sin(dLon/2)**2; return 2*R*Math.asin(Math.sqrt(x)) }

export default function HomePage(){
  const [posts,setPosts]=useState<Post[]>(demoPosts); const [composer,setComposer]=useState<'status'|'request'|null>(null); const [query,setQuery]=useState(''); const [filter,setFilter]=useState<'all'|'status'|'request'>('all'); const [toast,setToast]=useState(''); const [tab,setTab]=useState<'home'|'nearby'>('home'); const [profile,setProfile]=useState(false); const [location,setLocation]=useState<Loc|null>(null); const [nearbyOnly,setNearbyOnly]=useState(false); const notified=useRef<Set<string>>(new Set())
  const loadPosts=useCallback(async()=>{ if(!supabase){const local=JSON.parse(localStorage.getItem('status-now-local')||'[]') as Post[];setPosts([...local.filter(p=>new Date(p.expires_at).getTime()>Date.now()),...demoPosts]);return} const {data,error}=await supabase.from('posts').select('*').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(100);if(!error&&data)setPosts(data as Post[]) },[])
  function requestLocation(){ if(!navigator.geolocation){setToast('הדפדפן לא תומך במיקום');return} navigator.geolocation.getCurrentPosition(p=>{setLocation({latitude:p.coords.latitude,longitude:p.coords.longitude});setToast('המיקום הופעל');setTimeout(()=>setToast(''),1600)},()=>{setToast('לא אושרה גישה למיקום');setTimeout(()=>setToast(''),1800)},{enableHighAccuracy:true,timeout:8000}) }
  useEffect(()=>{loadPosts(); if(!supabase)return; const channel=supabase.channel('posts-realtime').on('postgres_changes',{event:'*',schema:'public',table:'posts'},()=>loadPosts()).on('postgres_changes',{event:'*',schema:'public',table:'comments'},()=>loadPosts()).on('postgres_changes',{event:'*',schema:'public',table:'likes'},()=>loadPosts()).subscribe(); return()=>{supabase.removeChannel(channel)}},[loadPosts])
  useEffect(()=>{ if(!location)return; posts.filter(p=>p.kind==='request'&&p.latitude!=null&&p.longitude!=null).forEach(p=>{const d=distanceKm(location,{latitude:p.latitude!,longitude:p.longitude!}); if(d<=3&&!notified.current.has(p.id)){notified.current.add(p.id); const body=`בקשה חדשה לידך: ${p.text.slice(0,90)}`; setToast(body); setTimeout(()=>setToast(''),3500); if(Notification.permission==='granted') new Notification('Status Now',{body}) }}) },[posts,location])
  const filtered=useMemo(()=>posts.filter(p=>{if(filter!=='all'&&p.kind!==filter)return false; const q=query.trim().toLowerCase(); if(q&&!p.text.toLowerCase().includes(q)&&!p.location_name.toLowerCase().includes(q))return false; if(nearbyOnly&&location&&p.latitude!=null&&p.longitude!=null)return distanceKm(location,{latitude:p.latitude,longitude:p.longitude})<=5; if(nearbyOnly&&location)return false; return true}),[posts,filter,query,nearbyOnly,location])
  const trending=useMemo(()=>{const words=new Map<string,number>();posts.forEach(p=>p.text.split(/\s+/).filter(w=>w.length>3).forEach(w=>words.set(w,(words.get(w)||0)+1)));const learned=[...words.entries()].sort((a,b)=>b[1]-a[1]).slice(0,3).map(([w])=>w);return [...new Set([...learned,'איילון','רישוי','חופים','נתב״ג'])].slice(0,5)},[posts])
  function created(){loadPosts();setToast('פורסם בהצלחה');setTimeout(()=>setToast(''),1800)}
  async function enableAlerts(){ if(!('Notification' in window)){setToast('התראות דפדפן אינן נתמכות');return} const p=await Notification.requestPermission();setToast(p==='granted'?'התראות בסביבה הופעלו':'ההתראות לא אושרו');setTimeout(()=>setToast(''),1800) }
  return <main className="app-shell"><header className="topbar"><div className="topbar-inner"><div className="brand-row"><div className="brand">Status Now</div><div className="header-tools"><button className="round-tool" onClick={enableAlerts} aria-label="התראות"><BellRing size={17}/></button><div className="live-pill"><span className="live-dot"/>LIVE</div></div></div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="מה אתה רוצה לדעת עכשיו?"/></div></header><div className="container">{tab==='home'?<><div className="trending">{trending.map(x=><button key={x} className="trend" onClick={()=>setQuery(x)}>🔥 {x}</button>)}</div><div className="actions"><button className="primary-action" onClick={()=>setComposer('status')}>＋ פרסם סטטוס</button><button className="secondary-action" onClick={()=>setComposer('request')}>? בקש סטטוס</button></div>{!hasSupabaseEnv&&<p className="helper demo-note">מצב הדגמה פעיל. לאחר חיבור Supabase הנתונים יישמרו וישודרו בזמן אמת.</p>}<div className="location-strip"><button onClick={requestLocation}><LocateFixed size={16}/>{location?'המיקום פעיל':'הפעל מיקום'}</button><button className={nearbyOnly?'active':''} disabled={!location} onClick={()=>setNearbyOnly(v=>!v)}>עד 5 ק״מ ממני</button></div><div className="filter-row"><button className={`filter ${filter==='all'?'active':''}`} onClick={()=>setFilter('all')}>הכל</button><button className={`filter ${filter==='status'?'active':''}`} onClick={()=>setFilter('status')}>עדכונים</button><button className={`filter ${filter==='request'?'active':''}`} onClick={()=>setFilter('request')}>בקשות</button></div><Feed posts={filtered} onRefresh={loadPosts}/></>:<><div className="section-title"><div><h2>מה קורה סביבי</h2><p>עדכונים ובקשות לפי המיקום שלך</p></div><button className="location-cta" onClick={requestLocation}><LocateFixed size={17}/>{location?'רענן מיקום':'הפעל GPS'}</button></div><NearbyMap posts={posts} userLocation={location}/></>}</div><nav className="bottom-nav"><div className="bottom-inner"><button className={`nav-item ${tab==='home'?'active':''}`} onClick={()=>setTab('home')}><Home size={20}/>בית</button><button className={`nav-item ${tab==='nearby'?'active':''}`} onClick={()=>{setTab('nearby');if(!location)requestLocation()}}><MapPinned size={20}/>סביבי</button><button className="nav-item" onClick={()=>setProfile(true)}><UserRound size={20}/>פרופיל</button></div></nav>{composer&&<Composer mode={composer} onClose={()=>setComposer(null)} onCreated={created} userLocation={location}/>} {profile&&<AuthPanel onClose={()=>setProfile(false)}/>} {toast&&<div className="toast">{toast}</div>}</main>
}
